# Generated by Django 5.0.12 on 2025-09-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=1024)),
                ('approximate_rate', models.DecimalField(decimal_places=2, help_text='Approximate rate per person per night (single bed, in local currency) in ZAR.', max_digits=8)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=1024)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('shuttle_service', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('contact', 'Contact to confirm')], default='contact', max_length=10)),
                ('breakfast_included', models.BooleanField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='website.accommodationtype')),
            ],
        ),
    ]
