# Generated by Django 5.0.12 on 2025-06-12 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaInvitationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('participant_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('registration_type', models.CharField(default='Attendee', max_length=50)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('is_speaker', models.BooleanField(default=False)),
                ('presentation_title', models.CharField(blank=True, max_length=255, null=True)),
                ('embassy_address', models.TextField(default='Embassy of South Africa')),
                ('organizer_name', models.CharField(default='PyCon Africa 2025 Organizing Committee', max_length=255)),
                ('organizer_role', models.CharField(default='Conference Chair', max_length=100)),
                ('contact_email', models.EmailField(default='team@pycon.africa', max_length=254)),
                ('contact_phone', models.CharField(default='+27 XX XXX XXXX', max_length=20)),
                ('conference_location', models.CharField(default='Johannesburg, South Africa', max_length=100)),
                ('conference_dates', models.CharField(default='October 8-12, 2025', max_length=100)),
                ('website_url', models.URLField(default='africa.pycon.org')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visa_letters', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visa Invitation Letter',
                'verbose_name_plural': 'Visa Invitation Letters',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email', 'country_of_origin', 'arrival_date', 'departure_date'), ('user', 'participant_name', 'passport_number', 'arrival_date', 'departure_date')},
            },
        ),
    ]
