# Generated by Django 5.0.12 on 2025-05-19 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(help_text='Explain why you would like to attend PyCon Africa and how it would benefit you.')),
                ('contribution', models.TextField(help_text='Describe any contributions you have made to Python, PyCon Africa, or the broader tech community.')),
                ('financial_need', models.TextField(help_text='Please explain your financial circumstances and why you need this grant.')),
                ('request_travel', models.BooleanField(default=False, help_text='Do you need assistance with travel costs?')),
                ('travel_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated travel costs in USD', max_digits=10, null=True)),
                ('travel_from', models.CharField(blank=True, help_text='Where will you be traveling from?', max_length=255)),
                ('request_accommodation', models.BooleanField(default=False, help_text='Do you need assistance with accommodation?')),
                ('accommodation_nights', models.PositiveIntegerField(blank=True, help_text='Number of nights you need accommodation for', null=True)),
                ('request_ticket', models.BooleanField(default=False, help_text='Do you need a conference ticket?')),
                ('status', models.CharField(choices=[('submitted', 'Application Submitted'), ('under_review', 'Application Under Review'), ('approved', 'Application Approved'), ('rejected', 'Application Rejected'), ('accepted', 'Grant Accepted by Applicant'), ('declined', 'Grant Declined by Applicant')], default='submitted', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal notes for reviewers')),
                ('amount_granted', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount granted in USD', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grant_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_review_grants', 'Can review grant applications'),),
            },
        ),
    ]
