# Generated by Django 5.0.12 on 2025-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='Is there anything else not covered above you would like to tell us?'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='conference_benefit',
            field=models.TextField(default='Not specified', help_text='How do you hope attending the PyCon Africa 2024 Conference will benefit you?'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='current_role',
            field=models.CharField(choices=[('high_school_student', 'High School Student'), ('undergraduate_student', 'Undergraduate Student'), ('graduate_student', 'Graduate Student'), ('employed', 'Employed'), ('self_employed', 'Self-employed/Freelancer'), ('between_jobs', 'Between jobs/Seeking opportunities'), ('retired', 'Retired'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], default='prefer_not_to_say', help_text='Which of the following best describes your current role?', max_length=30),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='current_role_details',
            field=models.TextField(blank=True, default='', help_text="Please provide more details if you selected 'Other'"),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], default='prefer_not_to_say', help_text='Gender identity', max_length=20),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='gender_details',
            field=models.TextField(blank=True, default='', help_text="Please provide more details if you selected 'Other'"),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='phone_number',
            field=models.CharField(default='', help_text='Your phone number for contact purposes', max_length=20),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='talk_proposal',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('other', 'Other')], default='no', help_text='Have you submitted a talk proposal?', max_length=20),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='talk_proposal_details',
            field=models.TextField(blank=True, default='', help_text="Please provide more details if you selected 'Other'"),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='transportation_type',
            field=models.CharField(blank=True, choices=[('air_travel', 'Air travel'), ('ground_travel', 'Ground travel (bus, car, train)')], default='', help_text='What type of transportation were you planning to take?', max_length=20),
        ),
    ]
