# Generated by Django 5.0.12 on 2025-05-30 19:09

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_grantapplication_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='travel_from',
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='travel_from_city',
            field=models.CharField(blank=True, default='', help_text='City you will be traveling from', max_length=100),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='travel_from_country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country you will be traveling from', max_length=2, null=True),
        ),
    ]
