# Generated by Django 5.0.12 on 2025-05-30 20:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_remove_grantapplication_travel_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantapplication',
            options={'permissions': (('can_review_grants', 'Can review grant applications'), ('can_make_grant_decisions', 'Can make final grant decisions'))},
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='decision_maker',
            field=models.ForeignKey(blank=True, help_text='User who made the final decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='decision_notes',
            field=models.TextField(blank=True, help_text='Final decision notes from decision maker'),
        ),
        migrations.CreateModel(
            name='GrantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Reviewer notes and feedback')),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Suggested grant amount in USD', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='grants.grantapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('application', 'reviewer')},
            },
        ),
    ]
