# Generated by Django 5.0.12 on 2025-06-04 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_alter_grantapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='amount_granted',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='conference_benefit',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='decision_maker',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='decision_notes',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='reviewer_notes',
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='phone_number',
            field=models.CharField(default='', help_text='Your phone number for contact purposes', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format: +[country code][number]', regex='^\\+[1-9]\\d{8,14}$')]),
        ),
        migrations.DeleteModel(
            name='GrantReview',
        ),
    ]
